DROP TABLE azziedev_tigertalks.flaggedcomment;
DROP TABLE azziedev_tigertalks.flaggedpost;
DROP TABLE azziedev_tigertalks.follow;
DROP TABLE azziedev_tigertalks.comment;
DROP TABLE azziedev_tigertalks.post;
DROP TABLE azziedev_tigertalks.tigerspace;
DROP TABLE azziedev_tigertalks.faculty;
DROP TABLE azziedev_tigertalks.student;
DROP TABLE azziedev_tigertalks.user;
